### ISSUE TITLE
Unisphere PowerMax 3 - Issue with Array WP Cache and Health Score

### ISSUE THREAD

**Issue by meni2029** [kuhn-ruess/Checkmk-Checks#96]
I'm testing unisphere_powermax latest version (3.0.3) on Checkmk 2.3. Service check "Array WP Cache" and "Health Score" are failing.

I found the following errors:

- `check_level` instead of `check_levels` in unisphere_powermax_array_performance.py
https://github.com/kuhn-ruess/Checkmk-Checks/blob/63fca40bab0d10c532a91615df2a83a8c11d2195/unisphere_powermax/src/unisphere_powermax/agent_based/unisphere_powermax_array_performance.py#L48
https://github.com/kuhn-ruess/Checkmk-Checks/blob/63fca40bab0d10c532a91615df2a83a8c11d2195/unisphere_powermax/src/unisphere_powermax/agent_based/unisphere_powermax_array_performance.py#L55

- rulespec name error for powermax_array_performance_wp_cache in rulesets.py
https://github.com/kuhn-ruess/Checkmk-Checks/blob/63fca40bab0d10c532a91615df2a83a8c11d2195/unisphere_powermax/src/unisphere_powermax/rulesets/rulesets.py#L256

- `check_levels` not imported in unisphere_powermax_health_score.py
https://github.com/kuhn-ruess/Checkmk-Checks/blob/63fca40bab0d10c532a91615df2a83a8c11d2195/unisphere_powermax/src/unisphere_powermax/agent_based/unisphere_powermax_health_score.py#L9

**Comment by Bastian-Kuhn** [comment]
Hi, yes this checks are a piece of work. Sorry for the trouble, and thank you for testing.
I'm in the middle of modernizing them and had to deal with an old code base, which even includes a check that I either don't understand or that makes no sense. I'm also sure that one section in the agent never worked before because of a / instead of a point.  

The problem is, right now I can't test it. I work with stored agent outputs. 
Can you please check out the 3.0.4 to see if there are any exceptions?

Also, I added a migrate function for the rulesets. So the old config with the invalid names should still work.
But the agent code still contains a lot of invalid variable names; don't have the time to change and test them all. 

Thanks in advance for any update and your help.

**Comment by meni2029** [comment]
Hi, thanks for your feedback.

With versions 3.0.4 and 3.0.5 I got exceptions about **No Cert Check** option, but then it works with version 3.0.6 :)

With 3.0.6 I get at discovery
- WARNING: Parsing of section unisphere_powermax_port_group failed
- WARNING: Parsing of section unisphere_powermax_alerts failed

With 3.0.6-dev2 I get exception:
- AttributeError: 'Namespace' object has no attribute 'disableget_srp_info'. Did you mean: 'disable_get_srp_info'?

I tested only on Checkmk2.3

**Comment by Bastian-Kuhn** [comment]
Hi,

at least one who can test this plugin :)
I still have to work "blind".

In the dev-x versions, the whole agent is adapted to Python standards.
The problem with the disable without _ was in the 3.0.6, but dev-2 changed that in fact to disable_get_srp_info.
If you still get this error, it could be a cache problem. Could you restart OMD once? And then just open and save the Unisphere Agent rule.

Does this Fix the error?
I don't know if there will be further errors from there. Therefore I'm gratefull for you testing.

For the Discovery:
Hopefully you wil be back at these errors after the Namespace problem is gone.

Can you then do the discovery on the Commandline with cmk --debug -IIv YOURHOSTNAMe.

Then you should see an exception wich would help me to fix the parsing error.

Or maybe you could send an agent output to us? Then I can reproduce that.

**Comment by Bastian-Kuhn** [comment]
I just tested your agent output with the latest version of the Plugin, 
no error at all. 

I guess the only thing now to do , is to make it configurable with API is to use.

**Comment by meni2029** [comment]
Yes, ability to configure which api version to use would be useful. 

I still want to check why <<<unisphere_powermax_health_check>>> was empty in my output, when I have an occasion.

**Comment by meni2029** [comment]
Thanks @Bastian-Kuhn !
We can close this issue
